### ISSUE TITLE
possible bug in the get_maxes function in data.py

### ISSUE THREAD

**Issue by RGaonkar** [atcbosselut/scs-baselines#1]
As far as I can see, this is the snippet under the get_maxes function in the latest version of the code:

> 
       if ents:
            for story, ent_list in data.iteritems():
                maximum = max(maximum, len(ent_list))
                print len(ent_list)
        if not ctx:
            for listed in data:
                maximum = max(len(listed), maximum)
            return maximum 
>
The function enters both the if conditions `if ents` and `if not ctx` when calling `self.ent_maxes[split] = self.get_maxes(num_ents, ents=True)`. So, in the first if condition, the correct maximum is obtained. As soon as it enters the second if condition, it overwrites the `maximum` with the length of the storyid string length - for e.g. "eb992af2-4316-4bf7-bf30-c3a11ab0b1c1" which is of length 36. My suggestion is to return at the end of the first if condition, to get correct maximum for the number of entities.

**Comment by atcbosselut** [comment]
Thanks for pointing this out and proposing a solution.

This was an artifact left from an older version of the codebase. ```ents``` is only true when maxes are computed for a variable that is no longer used downstream. I've removed that part.
